# Generated by Django 4.0.4 on 2022-06-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128)),
                ('myimg', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Studimg',
            },
        ),
        migrations.RemoveField(
            model_name='empp',
            name='myimg',
        ),
    ]
